2020-01-11

Core was generated by `./my_sipp -sn uas -trace_msg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055859116b6ec in std::vector<message*, std::allocator<message*> >::size (this=0x18) at /usr/include/c++/7/bits/stl_vector.h:671
671           { return size_type(this->_M_impl._M_finish - this->_M_impl._M_start); }
(gdb) bt
#0  0x000055859116b6ec in std::vector<message*, std::allocator<message*> >::size (this=0x18) at /usr/include/c++/7/bits/stl_vector.h:671
#1  0x000055859116b4d3 in scenario::runInit (this=0x0) at scenario.cpp:151
#2  0x000055859116aa68 in main (argc=4, argv=0x7fff3cb556e8) at sipp.cpp:405

2020-01-11 17:40
加
        /*
        while (sockets_pending_reset.begin() != sockets_pending_reset.end()) {
            reset_connection(*(sockets_pending_reset.begin()));
            sockets_pending_reset.erase(sockets_pending_reset.begin());
        }
        */

        /* Update the clock. */
        getmilliseconds();
        /* Receive incoming messages */
        if(MODE_SERVER == sendMode)
    	{
    		pollset_process(running_tasks->empty());
    	}

client重传invite

2020-01-18
gdb sipp client信息
第一次 run  : screentask::run()
第二次 run  : bool watchdog::run()  
第三次 run  : bool CallGenerationTask::run()      call_generation_task.cp:93
第三次 run  : bool call::run()                    call.cpp:1570                   执行完毕后，server收到invite消息，并回消息

修改CallGenerationTask::run(), socketowner.cpp没编译通过

2020-01-28
完成编译，待验证一次invite-200OK流程

2020-01-29
完善 call::send_scene，编译通过，待验证一次invite-200OK流程

2020-01-30
完善 SendingMessage::SendingMessage，编译通过，待验证一次invite-200OK流程

16:47 client能发送invite，但是server端收不到，invite消息可能有错误
17:53 client能发送invite，但是server端收不到，invite消息可能有错误，
      server端走到 empty_socket，recvfrom ret: 503, socket->ss_fd: 4, 产生crash, check_for_message 还没加






































